export const SEARCH_CATEGORIES = [
  {
    name: "Art & Culture",
    id: 8,
    dbTypeName: "Art&Culture",
    bgImage: "/images/categories/art/background.jpg",
    mapImage: "/images/categories/art/map.png",
    icon: "/images/categories/art/icon.svg",
    searchUrl: "/search/art-culture",
  },
  {
    name: "Hotel",
    id: 5,
    dbTypeName: "Hôtel",
    bgImage: "/images/categories/hotel/background.jpg",
    mapImage: "/images/categories/hotel/map.png",
    icon: "/images/categories/hotel/icon.svg",
    searchUrl: "/search/hotel",
  },
  {
    name: "Parks & Loisirs",
    id: 4,
    dbTypeName: "Park&Loisirs",
    bgImage: "/images/categories/park/background.jpg",
    mapImage: "/images/categories/park/map.png",
    icon: "/images/categories/park/icon.svg",
    searchUrl: "/search/park",
  },
  {
    name: "Monument",
    id: 6,
    dbTypeName: "Monument",
    bgImage: "/images/categories/monument/background.jpg",
    mapImage: "/images/categories/monument/map.png",
    icon: "/images/categories/monument/icon.svg",
    searchUrl: "/search/monument",
  },
  {
    name: "Mosque",
    id: 1,
    dbTypeName: "Mosquée",
    bgImage: "/images/categories/mosque/background.jpg",
    mapImage: "/images/categories/mosque/map.png",
    icon: "/images/categories/mosque/icon.svg",
    searchUrl: "/search/mosque",
  },
  {
    name: "Shopping",
    id: 10,
    dbTypeName: "Shopping",
    bgImage: "/images/categories/shopping/background.jpg",
    mapImage: "/images/categories/shopping/map.png",
    icon: "/images/categories/shopping/icon.svg",
    searchUrl: "/search/shopping",
  },
  {
    name: "Service",
    id: 9,
    dbTypeName: "Service",
    bgImage: "/images/categories/service/background.jpg",
    mapImage: "/images/categories/service/map.png",
    icon: "/images/categories/service/icon.svg",
    searchUrl: "/search/service",
  },
  {
    name: "Directories",
    id: 2,
    dbTypeName: "Annuaires",
    bgImage: "/images/categories/directories/background.jpg",
    mapImage: "/images/categories/directories/map.png",
    icon: "/images/categories/directories/icon.svg",
    searchUrl: "/search/directories",
  },
  {
    name: "Museum",
    id: 7,
    dbTypeName: "Musée",
    bgImage: "/images/categories/museum/background.jpg",
    mapImage: "/images/categories/museum/map.png",
    icon: "/images/categories/museum/icon.svg",
    searchUrl: "/search/museum",
  },
  {
    name: "Restaurant",
    id: 3,
    dbTypeName: "Restaurant",
    bgImage: "/images/categories/restaurant/background.jpg",
    mapImage: "/images/categories/restaurant/map.png",
    icon: "/images/categories/restaurant/icon.svg",
    searchUrl: "/search/restaurant",
  },
];
